accounts/urls.py
from . import views
from django.urls import path


app_name ='accounts'

urlpatterns = [
    path('',views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('user/', views.user_view, name='user'),
    path('profile/', views. update_user_view,name='profile'),
    path('users/',views.list_users,name ='users'),
    path('logout', views.logout_view, name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path('',RedirectView.as_view(url='/accounts/')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from  django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):

    first_name = models.CharField(_("first name"), max_length=150, blank=False)
    last_name = models.CharField(_("last name"), max_length=150, blank=False)
    email = models.EmailField(_("email address"), blank=False,unique=True)

    image = models.ImageField("imagen",
        upload_to='profile_pics/',  # Carpeta donde se almacenarán las imágenes
        default='profile_pics/default.png',  # Imagen por defecto
        blank=True,  # Campo opcional
        null=True    # Permitir valores nulos
    )
    
    REQUIRED_FIELDS = ["email","first_name","last_name"]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model

CustomUser = get_user_model()


class LoginForm(AuthenticationForm):
    pass
    
 
class CustomUserUpdateForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):
        super(CustomUserUpdateForm,self).__init__(*args,**kwargs)
        self.fields['last_login'].widget.attrs['readonly'] = True
        self.fields['date_joined'].widget.attrs['readonly'] = True

    class Meta:
        model = CustomUser
        fields = ['username','image','first_name','last_name', 'email','last_login', 'date_joined']

accounts/views.py
from django.shortcuts import render,redirect
from .forms import LoginForm
#from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required,permission_required
#from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import CustomUser as User
from .forms import  CustomUserUpdateForm


def home_view(request):
    return render(request,'accounts/home.html')

@login_required(login_url='/accounts/login/')
def logout_view(request):
    logout(request)
    messages.info(request,"salida exitosa!")
    return render(request, 'accounts/logout.html')


@login_required(login_url='/accounts/login/')
@permission_required('is_superuser',login_url='/accounts/user/')
def list_users(request):

    users = User.objects.all()

    context = {'users': users}
    return render(request,'accounts/list_users.html',context)


def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('accounts:user'))
      
    if request.method == 'POST':
    
        form = LoginForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()

            if user:
                login(request, user)
                messages.success(request,"login successful!")
                return redirect(reverse('accounts:user'))
            
        else:
        	messages.error(request, 'Error al introducir los datos	.')        
            
    else:
        form = LoginForm()
    
    param = {
        'form': form,
    }
  
    return render(request, 'accounts/login.html', param)

@login_required(login_url='/accounts/login/')
def user_view(request):
   
    return render(request, 'accounts/user.html')



@login_required(login_url='/accounts/login/')
def update_user_view(request):
    if request.method == 'POST':
        form = CustomUserUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Perfil actualizado exitosamente.')
            return redirect(reverse('accounts:profile')) 
        else:
         messages.error(request, 'Error al intentar actualizar el formulario.')     
    else:
        form = CustomUserUpdateForm(instance=request.user)

    return render(request, 'accounts/profile.html', {'form': form})    
    
    
    
    

templates/accounts/home.html
{%  extends 'base.html'%}
{% load static %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" >
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img   src="{% static 'home/1_.jpg' %}"  class="d-block w-100" alt="..." style="height: 70vh;">
    </div>
    <div class="carousel-item"> 
      <img  src="{% static 'home/2_.png' %}" class="d-block w-100" alt="..." style="height: 70vh;"  >
    </div>
   
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>



{% endblock %}

templates/accounts/list_users.html
{% extends 'base.html' %}

{% block content %}


   
  </ul>

    <ul>
    

        <ul class="list-group">
            <a href="#" class="list-group-item list-group-item-action active">
                Cras justo odio
              </a>
              {% for user in users %}
                    <li class="list-group-item ">username: {{ user.username }} 
                        email: {{user.email          }}</li>
                {% endfor %}
    </ul>

{% endblock%}

templates/accounts/login.html
{%  extends 'base.html'%}
{% load crispy_forms_tags %}

{% block  title %}
    <title>Login</title>
{% endblock %}

{% block content %}

  
<h1 class="text-center my-4">Login</h1>
<div class="container">
    <div class="row justify-content-center">
        <!-- Hacemos el formulario más pequeño y centrado -->
        <div class="col-md-4 col-sm-8">
            <form action="{% url 'accounts:login' %}" method="post" class="shadow p-4 rounded bg-light">
                {% csrf_token %}
                {{ form|crispy }} 
                <p class="text-center mt-3">
                    <input type="submit" class="btn btn-primary w-100" value="ENTRAR">
                </p>
            </form>
        </div>
    </div>
</div>

     
{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}

{% block  title %}
    <title>Logout</title>
{% endblock %}

{%  block content %}

<div class="card">
    <div class="card-header">
      Quote
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <a href="{% url 'accounts:login' %}" class="nav-link">Volver a logearse</a>
        <a href="{% url 'accounts:home' %}" class="nav-link">Home page</a>

        <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
      </blockquote>
    </div>
  </div>

{% endblock %}

templates/accounts/profile.html
{%  extends 'base.html'%}
{% load crispy_forms_tags %}

{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }} 
        <p><input type="submit" class="btn btn-primary" value="ACTUALIZAR"></p>
    </form>

{% endblock%}

templates/accounts/user.html
{% extends 'base.html'%}

{% block  title %}
    <title>Profile</title>
{% endblock %}

{% block content %}


<div class="card">
 
    <div class="card-header">
      Featured
    </div>
    <div class="card-body">

      <h5 class="card-title">Username: {{user.username }} </h5>
      <img src="{{ user.image.url }}" alt="Profile Picture" style="max-width: 200px; border-radius: 50%;">
      
       <p class="card-text">Nombre: {{user.first_name}} {{ user.last_name}}</p>

       <p class="card-text">Email: {{user.email}}</p>
      <a href="{% url 'accounts:profile'%}" class="btn btn-primary">Editar</a>
    </div>
  </div>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block  title %}{% endblock %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    <style>

    .alert-container {
      position: fixed; /* Fija el contenedor en la pantalla */
      top: 55px; /* Distancia desde la parte superior */
      right: 20px; /* Distancia desde la parte derecha */
      z-index: 1050; /* Asegura que esté por encima de otros elementos */
      width: 300px; /* Ancho máximo del contenedor de alertas */
      pointer-events: none; /* Permite hacer clic a través del contenedor */
    }

    .alert {
      position: relative; /* Posiciona las alertas de forma relativa dentro del contenedor fijo */
      margin: 0; /* Elimina cualquier margen que pueda afectar el flujo de la página */
      margin-bottom: 10px; /* Añade espacio solo entre alertas */
      opacity: 0.9; /* Transparencia leve para diferenciarlo del contenido */
      transition: opacity 0.5s ease-out; /* Transición suave al desvanecer */
      pointer-events: auto; /* Habilita los clics dentro de los elementos de alerta */
    }

      .dropdown-menu {
         min-width: 6.4rem  ;
      }
      /* Agregar padding a los elementos de la navbar */
      .navbar-nav .nav-link {
          padding: 8px 15px; /* Más padding alrededor de los elementos del navbar */
          font-size: 0.9rem; /* Reducir tamaño de fuente */
      }

      /* Ajustar la altura de la navbar y espaciar los elementos */
      .navbar {
          padding: 0.5rem 1rem; /* Ajustar padding de la navbar */
      }

      /* Ajustes al contenido de la página */
      .container {
          padding-top: 20px; /* Más espacio en la parte superior */
          padding-bottom: 20px; /* Más espacio en la parte inferior */
      }

      /* Aumentar el espacio entre elementos de footer */
      footer {
          padding: 20px 0;
      }
  </style>  

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>   
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{%  url 'accounts:home' %}">

          <img src="{% static 'logo.png'%}" alt="logo" srcset="" width="35" height="35"
          style="border-radius: 50%;">
        </a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
         
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                
              {%  if request.resolver_match.url_name == 'home' %}

              <a class="nav-link active"  href="{%  url 'accounts:home' %}">HOME</a>
              {% else %}
              <a class="nav-link"  href="{%  url 'accounts:home' %}">HOME</a>
             {% endif %}
            </li>
            {% if user.is_authenticated %}
          
              {% if request.resolver_match.url_name == 'profile'%}
                <li class="nav-item">
                
                <a class="nav-link   active"  href="{%  url 'accounts:profile' %}">PROFILE</a>
              </li>
              
              {% else %}
                <li class="nav-item">
                
                <a class="nav-link link-light" href="{%  url 'accounts:profile' %}">PROFILE</a>
              </li>
              
              {% endif %}
              
             
    
              <li class="nav-item">
    
                {% if request.resolver_match.url_name == 'user' %}
              
                    <a class="nav-link link-light  active"   href="{% url 'accounts:user'%}">USER DATA</a> 
    
                 {% else %}
           <a class="nav-link link-light" href="{% url 'accounts:user'%}">USER DATA</a>
    
                 {% endif %}
              
              </li>
    
                    {% if  user.is_superuser %}
                    
                    <li class="nav-item">
                       {% if request.resolver_match.url_name == 'users'%}
                       
                       <a class="nav-link link-light  active"  href="{% url  'accounts:users'%}">USERS</a>
                    {%else %}
                    <a class="nav-link link-light" href="{% url  'accounts:users'%}">USERS</a>
                    {% endif%}
    
                   
                    </li>
                    
                    {%endif%}
            
           
          {% endif %}    
         
          </ul>

          <ul class="navbar-nav  justify-content-end">
            {% if   user.is_authenticated %}
            
            <div class="dropdown">
             
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Settings

              </button>
        
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item " href="{%  url 'accounts:logout' %}">
                  <span style="padding-right: 5px;">
                    SALIR
                  </span>
                
                  <i class="fa-solid fa-arrow-right-from-bracket"></i>
                </a> 
              </div>
              {%  else %}
              <li class="nav-item">
    
                {% if request.resolver_match.url_name == "login" %}
                    <a class="nav-link link-light  active"   href="{% url  'accounts:login'%}">LOGIN</a>
                {% else %}
                    <a class="nav-link link-light" href="{% url  'accounts:login'%}">LOGIN</a>
                    
                {% endif %}
              </li>
            
            
            </div>
        
           
            {% endif %}
           
  
          </ul>
            
        </div>
      </div>
    </nav>
    <div class="alert-container">
    {% if messages %}
        {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{message}}
                </div>
        {% endfor %}
    {% endif %}
  </div>
   
<div class="container  mt-4" style="min-height:50vh">
  {% block content %} 
    {% endblock %}  
</div>

<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% bootstrap_javascript %}
<script>
  document.addEventListener('DOMContentLoaded', function () {
    setTimeout(function () {
      var alertElements = document.querySelectorAll('.alert');
      alertElements.forEach(function (element) {
        element.style.opacity = '0'; // Cambia la opacidad para el desvanecimiento
        setTimeout(function () {
          element.remove(); // Elimina el elemento después de que se desvanezca
        }, 500); // Espera que termine la transición antes de eliminar
      });
    }, 3000); // Espera 3 segundos antes de iniciar el desvanecimiento
  });
</script>

</body>
</html>